name: Start ECS Service in the Morning

on:
  schedule:
    - cron: '45 9 * * *' # Runs at 9:45 AM UTC (10:45 AM BST / 5:45 AM ET)
  workflow_dispatch:

jobs:
  start-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Start ECS Service
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Start service
        run: |
          aws ecs update-service \
            --cluster splitclone-cluster \
            --service splitclone-service \
            --desired-count 1
