name: Stop ECS Service at Night

on:
  schedule:
    - cron: '0 0 * * *' # Runs at 8 PM UTC (9 PM BST / 4 PM ET)
  workflow_dispatch:

jobs:
  stop-ecs:
    runs-on: ubuntu-latest
    steps:
      - name: Stop ECS Service
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Stop service
        run: |
          aws ecs update-service \
            --cluster splitclone-cluster \
            --service splitclone-service \
            --desired-count 0
